### PR TITLE
Visual Studio 2019 update

### PR DESCRIPTION
**Pull request by LordKraken**
Same update as on Sage repo, and provide binaries that seem to work.
Also i had to fix strcmpi being absent on windows, and I replaced it with strcpmcase that sould be available on unix (and it fall back to _strcmpi on windows). 

But check linux build still.

### CODE REVIEW

**Comment by 42Bastian** [comment]
Ok, building works also for me.

**Comment by 42Bastian** [comment]
> yeah sorry, old windows coding habits :)
> I can amend the PR to change the folder names.

The project adds -x64 to the exe. I don't think it is needed. If we want to support both 32bit and 64bit version, then we might add a sub-folder. And maybe this way:
bin/win32/x64
bin/mingw/
bin/linux

**Review by 42Bastian — COMMENTED** [review]
Still not sure, why we need to have a debug version.
Actually I prefer a folder structure instead of flat version.

**Comment by LordKraken** [comment]
I'd say it's just a matter of taste, and I personally don't mind changing to what you like best. Just tell me :)

**Comment by 42Bastian** [comment]
Just did it. Also some clean up.

**Pull request merged**
